apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-server-route
  namespace: argocd
spec:
  parentRefs:
  - name: envoy-gateway
    namespace: gateway
  hostnames:
  - "argocd.example.com"
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80