apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/samuelbagattin/argocd-components.git
    targetRevision: HEAD
    path: envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true