apiVersion: v1
kind: Secret
metadata:
  name: argocd-components-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: "git"
  url: "https://github.com/samuelbagattin/argocd-components.git"